export interface WorkspaceDefinition {
  key: string;
  href: string;
  label: string;
  objective: string;
  accent: string;
  metrics: { label: string; field: "cases" | "records" | "reviews" | "findings" | "reports" | "users" }[];
  sections: { title: string; items: string[] }[];
  actions: { label: string; href: string }[];
}

export const WORKSPACES: Record<string, WorkspaceDefinition> = {
  ATTORNEY_CLIENT: { key: "ATTORNEY_CLIENT", href: "/attorney", label: "Attorney", objective: "Decide whether future medical damages justify an expert engagement and track released work product.", accent: "indigo", metrics: [{label:"Active matters",field:"cases"},{label:"Evidence gaps",field:"findings"},{label:"Released reports",field:"reports"}], sections: [{title:"Decision support",items:["Future-damages readiness","Supporting and weakening factors","Report option and engagement recommendation"]},{title:"Deliverables",items:["Released reports only","Approval and attestation status","Material uncertainty and disclaimers"]}], actions: [{label:"Review matters",href:"/cases"}] },
  CASE_MANAGER: { key:"CASE_MANAGER",href:"/case-manager",label:"Case Manager",objective:"Move matters through intake, record collection, assignments, deadlines, and escalations.",accent:"sky",metrics:[{label:"Open cases",field:"cases"},{label:"Records received",field:"records"},{label:"Open blockers",field:"findings"}],sections:[{title:"Intake queue",items:["Required intake fields","Authorizations and missing client details","Workflow stage and assignments"]},{title:"Coordination",items:["Provider and records requests","Deadlines and action items","Escalations and clarification requests"]}],actions:[{label:"Open case queue",href:"/cases"},{label:"Create case",href:"/cases"}]},
  MEDICAL_RECORD_ANALYST: { key:"MEDICAL_RECORD_ANALYST",href:"/records",label:"Records Analyst",objective:"Turn raw records into a reliable, structured, source-traceable record set.",accent:"cyan",metrics:[{label:"Documents",field:"records"},{label:"Extraction issues",field:"findings"},{label:"Active matters",field:"cases"}],sections:[{title:"Processing",items:["OCR and classification status","Provider, facility, date, and page metadata","Duplicates, corrupt files, and low confidence"]},{title:"Chronology QA",items:["Conflicting dates","Missing provider periods","Imaging, operative, therapy, and medication gaps"]}],actions:[{label:"Review records",href:"/cases"}]},
  LIFE_CARE_PLANNER: { key:"LIFE_CARE_PLANNER",href:"/planner",label:"Life Care Planner",objective:"Build defensible, traceable future-care recommendations and expert reports.",accent:"teal",metrics:[{label:"Active plans",field:"cases"},{label:"Items in review",field:"reviews"},{label:"Validation findings",field:"findings"}],sections:[{title:"Clinical plan",items:["Medical history and diagnoses","Future-care frequency, duration, cost, and rationale","Source evidence and conflicts"]},{title:"Report builder",items:["Report selection","Physician and interview requests","QA findings and revisions"]}],actions:[{label:"Open planner queue",href:"/cases"}]},
  PHYSICIAN_REVIEWER: { key:"PHYSICIAN_REVIEWER",href:"/physician",label:"Physician Reviewer",objective:"Independently review medical necessity and create credential-gated attestations.",accent:"emerald",metrics:[{label:"Pending items",field:"reviews"},{label:"Open cases",field:"cases"},{label:"Blocking findings",field:"findings"}],sections:[{title:"Independent review",items:["Diagnoses, chronology, imaging, and operative findings","Recommendation rationale and source evidence","Approve, reject, modify, or request clarification"]},{title:"Attestation",items:["Verified physician credential required","Immutable timestamped record","Amendment and withdrawal history"]}],actions:[{label:"Open review queue",href:"/review"}]},
  VOCATIONAL_EXPERT: { key:"VOCATIONAL_EXPERT",href:"/vocational",label:"Vocational Expert",objective:"Analyze work capacity, transferable skills, and vocational loss for engaged cases.",accent:"violet",metrics:[{label:"Engaged cases",field:"cases"},{label:"Open findings",field:"findings"},{label:"Reports",field:"reports"}],sections:[{title:"Vocational assessment",items:["Employment and education history","Functional restrictions and transferable skills","Return-to-work scenarios"]},{title:"Expert opinion",items:["Source-supported conclusions","Case-scoped access","Credential-gated attestation"]}],actions:[{label:"Open engagements",href:"/cases"}]},
  FORENSIC_ECONOMIST: { key:"FORENSIC_ECONOMIST",href:"/economist",label:"Forensic Economist",objective:"Model deterministic present-value medical and earning-loss scenarios.",accent:"amber",metrics:[{label:"Engaged cases",field:"cases"},{label:"Economic reports",field:"reports"},{label:"Open findings",field:"findings"}],sections:[{title:"Economic model",items:["Discount and inflation assumptions","Work-life and earnings scenarios","Present value with reproducible inputs"]},{title:"Review",items:["Sensitivity comparisons","Source provenance","Credential-gated economic attestation"]}],actions:[{label:"Open economic cases",href:"/cases"}]},
  QUALITY_ASSURANCE_REVIEWER: { key:"QUALITY_ASSURANCE_REVIEWER",href:"/qa",label:"Quality Assurance",objective:"Resolve completeness, consistency, citation, and export-blocking findings.",accent:"rose",metrics:[{label:"Open findings",field:"findings"},{label:"Reports awaiting QA",field:"reports"},{label:"Active cases",field:"cases"}],sections:[{title:"Integrity review",items:["Citation and source traceability","Clinical and cost consistency","Unsupported assumptions and missing approvals"]},{title:"Release gate",items:["Export-blocking findings","Revision comparison","Approval and attestation completeness"]}],actions:[{label:"Open QA queue",href:"/cases"}]},
  LEGACY_BILLING: { key:"LEGACY_BILLING",href:"/operations",label:"Billing & Operations",objective:"Manage subscriptions, invoices, utilization, and engagement operations without clinical access.",accent:"orange",metrics:[{label:"Firm seats",field:"users"},{label:"Active engagements",field:"cases"},{label:"Delivered reports",field:"reports"}],sections:[{title:"Commercial operations",items:["Subscription and seats","Engagement status and utilization","Invoice and delivery visibility"]},{title:"Separation of duties",items:["No clinical editing","No professional approval","No credential substitution"]}],actions:[{label:"Open billing",href:"/billing"}]},
  FIRM_ADMINISTRATOR: { key:"FIRM_ADMINISTRATOR",href:"/firm-admin",label:"Firm Administrator",objective:"Manage people, roles, offices, security, billing, and auditable firm configuration.",accent:"slate",metrics:[{label:"Users",field:"users"},{label:"Active cases",field:"cases"},{label:"Audit findings",field:"findings"}],sections:[{title:"Administration",items:["Team, seats, and role assignments","Offices, branding, retention, and features","Billing and audit export"]},{title:"Professional boundaries",items:["Credentials independently verified","Expert attestations remain gated","Tenant isolation enforced server-side"]}],actions:[{label:"Manage team",href:"/team"},{label:"Manage roles",href:"/roles"},{label:"Firm settings",href:"/settings"}]},
  PLATFORM_SYSTEM_ADMINISTRATOR: { key:"PLATFORM_SYSTEM_ADMINISTRATOR",href:"/platform-admin",label:"Platform Administrator",objective:"Operate tenant configuration and integrations without assuming a clinical identity.",accent:"zinc",metrics:[{label:"Tenant users",field:"users"},{label:"Cases",field:"cases"},{label:"System findings",field:"findings"}],sections:[{title:"Platform controls",items:["Tenant and feature configuration","Integration health","Platform audit visibility"]},{title:"Guardrails",items:["No expert impersonation","No silent tenant crossing","Every administrative action audited"]}],actions:[{label:"Audit log",href:"/settings/audit"}]},
  EXTERNAL_EXPERT: { key:"EXTERNAL_EXPERT",href:"/external-expert",label:"External Expert",objective:"Review only the specifically engaged cases and submit scoped expert work product.",accent:"lime",metrics:[{label:"Engaged cases",field:"cases"},{label:"Reports",field:"reports"},{label:"Open requests",field:"findings"}],sections:[{title:"Engagement",items:["Case-scoped evidence and chronology","Assigned expert questions","Credential upload and status"]},{title:"Deliverables",items:["Scoped work product","No firm-wide access","Released downloads only"]}],actions:[{label:"Open engagements",href:"/cases"}]},
  INSURANCE_CLIENT: { key:"INSURANCE_CLIENT",href:"/insurance",label:"Insurance Client",objective:"Review authorized damages posture and released deliverables for specifically engaged matters.",accent:"blue",metrics:[{label:"Engaged matters",field:"cases"},{label:"Released reports",field:"reports"},{label:"Open findings",field:"findings"}],sections:[{title:"Matter review",items:["Medical-cost posture","Released reports and status","Material assumptions and uncertainty"]},{title:"Restrictions",items:["Case-scoped access","No clinical editing","No unreleased drafts"]}],actions:[{label:"View matters",href:"/cases"}]},
  READ_ONLY_OBSERVER: { key:"READ_ONLY_OBSERVER",href:"/observer",label:"Read-only Observer",objective:"Inspect authorized matter status and released information without mutation rights.",accent:"gray",metrics:[{label:"Visible cases",field:"cases"},{label:"Reports",field:"reports"},{label:"Open findings",field:"findings"}],sections:[{title:"Observation",items:["Case status and chronology","Future care and costs","Approval and attestation status"]},{title:"Restrictions",items:["No edits","No approvals","No unreleased exports"]}],actions:[{label:"View cases",href:"/cases"}]},
};

export function workspaceHrefForRole(role?: string | null): string {
  return (role && WORKSPACES[role]?.href) || "/dashboard";
}
