import { prisma } from "@/lib/db";
import { generatePlanUnlocked, type PlanResult } from "@/lib/engine/generate";
import { persistCaseValidation } from "@/lib/engine/validation";
import { persistCaseReasoning } from "@/lib/engine/clinicalReasoningPersist";
import { refreshCaseAttestations } from "@/lib/engine/attestationService";
import { withCasePipelineLock, type PipelineLease, type PipelineLockOptions } from "@/lib/engine/pipelineLock";

// ─────────────────────────────────────────────────────────────────────────────
// The complete pipeline, as ONE unit of work under ONE lease.
//
// Generation was locked; everything downstream of it was not. The manual route
// did this:
//
//     const result = await generatePlan(caseId, actor);   // lock taken, released
//     await persistCaseValidation(caseId, firmId).catch(() => {});
//     await persistCaseReasoning(caseId, firmId).catch(() => {});
//     await refreshCaseAttestations(caseId).catch(() => {});
//
// Two defects follow from that shape.
//
// FIRST: the lock ends at the closing paren of `generatePlan`. The three
// finalizers then read a plan any other caller is free to be rewriting. The
// findings, the reasoning basis and the attestation verdicts could all be
// computed against a plan that no longer existed by the time they were
// persisted — a validation finding naming a recommendation that had just been
// superseded, an attestation re-verified against a half-written item set.
//
// SECOND, and worse: the coalescing loop lives INSIDE `generatePlan`. When an
// edit arrived mid-run, the holder made another generation pass — and that
// final pass had no finalizers after it at all, because the caller's three
// lines had already been queued against the first one. The plan a reviewer saw
// was generated by pass two and validated as pass one. The background callers
// never ran the finalizers in the first place, so a records correction produced
// a regenerated plan whose findings and attestations still described the plan
// before it.
//
// So the unit of work is not "generate". It is "generate, then validate, then
// persist reasoning, then re-verify attestations" — and the coalescing loop
// re-runs THAT, so whatever pass turns out to be last is the one the finalizers
// see. Every caller, manual or background, enters here.
// ─────────────────────────────────────────────────────────────────────────────

export interface PipelineActor {
  userId?: string;
  role?: string;
}

export interface PipelineOutcome extends PlanResult {
  /** How many complete passes ran, including coalesced re-runs. */
  passes: number;
  /** Finalizers that failed. Best-effort by contract, never silent. */
  finalizerErrors: { stage: string; message: string }[];
}

/** A finalizer's failure must not lose the generated plan, but must be visible. */
async function runFinalizer(
  stage: string,
  caseId: string,
  lease: PipelineLease,
  errors: { stage: string; message: string }[],
  fn: () => Promise<unknown>,
): Promise<void> {
  // Checked before every stage, not once at the top: a long generation may
  // have lost the lease while it ran, and persisting findings for a plan
  // another run is currently rewriting is exactly the race this prevents.
  lease.assertOwned();
  try {
    await fn();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    errors.push({ stage, message });
    // The case id and the stage, never the payload: a finalizer error can
    // carry record content, and a log line is the wrong place for it.
    console.error(`[pipeline] ${stage} failed for case ${caseId}: ${message.slice(0, 200)}`);
  }
}

/**
 * Generate the plan and everything that must see its output, under one lease.
 *
 * Throws PipelineBusyError when another run holds the case — the caller's
 * intent is recorded and the holder makes another complete pass, so nothing is
 * lost. Throws PipelineLeaseLostError if the lease was taken mid-run, having
 * written nothing further.
 */
export async function runCasePipeline(
  caseId: string,
  firmId: string,
  actor?: PipelineActor,
  options?: PipelineLockOptions,
): Promise<PipelineOutcome> {
  let passes = 0;
  return withCasePipelineLock(
    prisma,
    caseId,
    async (lease) => {
      passes += 1;
      // Errors are per-pass: a finalizer that failed against a superseded plan
      // says nothing about the plan that replaced it.
      const finalizerErrors: { stage: string; message: string }[] = [];

      const result = await generatePlanUnlocked(caseId, actor);

      // Persist the integrity findings for the fresh plan so the review
      // workflow can show them without building a report.
      await runFinalizer("validation", caseId, lease, finalizerErrors, () => persistCaseValidation(caseId, firmId));
      // Clinical Reasoning Engine — assess every recommendation of the fresh
      // plan so the structured assessment backs the narrative.
      await runFinalizer("reasoning", caseId, lease, finalizerErrors, () => persistCaseReasoning(caseId, firmId));
      // Regeneration can materially change signed-over recommendations —
      // re-verify active attestations (EPIC-005).
      await runFinalizer("attestations", caseId, lease, finalizerErrors, () => refreshCaseAttestations(caseId));

      return { ...result, passes, finalizerErrors } satisfies PipelineOutcome;
    },
    options,
  );
}
