import { describe, it, expect, vi, beforeEach } from "vitest";

// ─────────────────────────────────────────────────────────────────────────────
// The defect: the lock ended at the closing paren of `generatePlan`, and the
// three finalizers ran after it.
//
//   const result = await generatePlan(caseId, actor);   // lock taken, released
//   await persistCaseValidation(...).catch(() => {});
//   await persistCaseReasoning(...).catch(() => {});
//   await refreshCaseAttestations(...).catch(() => {});
//
// Two consequences, both tested here:
//
//   1. The finalizers read a plan any other caller was free to be rewriting.
//   2. The coalescing loop lives INSIDE the lock, so when an edit arrived
//      mid-run the holder made a SECOND generation pass — and that final pass
//      had no finalizers after it at all. The plan a reviewer saw was
//      generated by pass two and validated as pass one.
//
// The order of recorded stages is the whole point, so these tests record a
// single interleaved trace rather than asserting call counts in isolation.
// ─────────────────────────────────────────────────────────────────────────────

const trace: string[] = [];

/** One mutable row, so the lock's predicate semantics are real. */
const row = {
  id: "case-1",
  pipelineRunId: null as string | null,
  pipelineRunAt: null as Date | null,
  pipelineRerunRequested: false,
};

const caseStore = {
  async updateMany({ where, data }: { where: Record<string, unknown>; data: Record<string, unknown> }) {
    if (where.id !== undefined && where.id !== row.id) return { count: 0 };
    if (where.pipelineRunId !== undefined && where.pipelineRunId !== row.pipelineRunId) return { count: 0 };
    const or = where.OR as { pipelineRunId?: null; pipelineRunAt?: { lt: Date } }[] | undefined;
    if (or) {
      const free = or.some((c) => ("pipelineRunId" in c ? row.pipelineRunId === null : !!c.pipelineRunAt && row.pipelineRunAt !== null && row.pipelineRunAt < c.pipelineRunAt.lt));
      if (!free) return { count: 0 };
    }
    Object.assign(row, data);
    return { count: 1 };
  },
  async findUnique() {
    return { pipelineRunId: row.pipelineRunId, pipelineRerunRequested: row.pipelineRerunRequested };
  },
};

vi.mock("@/lib/db", () => ({ prisma: { case: caseStore } }));

let generateImpl: () => Promise<void> = async () => {};
let validationImpl: () => Promise<void> = async () => {};

vi.mock("@/lib/engine/generate", () => ({
  generatePlanUnlocked: vi.fn(async () => {
    trace.push("generate");
    await generateImpl();
    return { conditions: 9, chronology: 100, futureCare: 34, totalLifetime: 1, totalPresentValue: 1, superseded: 0 };
  }),
}));
vi.mock("@/lib/engine/validation", () => ({
  persistCaseValidation: vi.fn(async () => {
    trace.push("validation");
    await validationImpl();
  }),
}));
vi.mock("@/lib/engine/clinicalReasoningPersist", () => ({
  persistCaseReasoning: vi.fn(async () => { trace.push("reasoning"); }),
}));
vi.mock("@/lib/engine/attestationService", () => ({
  refreshCaseAttestations: vi.fn(async () => { trace.push("attestations"); }),
}));

const { runCasePipeline } = await import("@/lib/engine/runPipeline");
const { PipelineBusyError } = await import("@/lib/engine/pipelineLock");

beforeEach(() => {
  trace.length = 0;
  row.pipelineRunId = null;
  row.pipelineRunAt = null;
  row.pipelineRerunRequested = false;
  generateImpl = async () => {};
  validationImpl = async () => {};
  vi.spyOn(console, "error").mockImplementation(() => {});
});

describe("runCasePipeline", () => {
  it("runs generation and every finalizer, in order, as one pass", async () => {
    const out = await runCasePipeline("case-1", "firm-1");
    expect(trace).toEqual(["generate", "validation", "reasoning", "attestations"]);
    expect(out.passes).toBe(1);
    expect(out.finalizerErrors).toEqual([]);
  });

  it("holds the lock across the finalizers, not just generation", async () => {
    const heldAt: (string | null)[] = [];
    validationImpl = async () => { heldAt.push(row.pipelineRunId); };
    await runCasePipeline("case-1", "firm-1");
    // The old code released before this ran, so the claim was null here.
    expect(heldAt[0]).not.toBeNull();
  });

  it("releases the lock once the finalizers are done", async () => {
    await runCasePipeline("case-1", "firm-1");
    expect(row.pipelineRunId).toBeNull();
  });

  // THE regression. An edit lands during generation; the holder must make
  // another COMPLETE pass, so the finalizers describe the plan that actually
  // exists rather than the one two passes ago.
  it("finalizes the final coalesced pass, not the first", async () => {
    let generated = 0;
    generateImpl = async () => {
      generated += 1;
      if (generated === 1) row.pipelineRerunRequested = true;
    };
    const out = await runCasePipeline("case-1", "firm-1");
    expect(out.passes).toBe(2);
    expect(trace).toEqual([
      "generate", "validation", "reasoning", "attestations",
      "generate", "validation", "reasoning", "attestations",
    ]);
    // The property the old shape could not provide at all: every finalizer
    // runs AFTER the last generation, so none of them describes a superseded
    // plan.
    const lastGenerate = trace.lastIndexOf("generate");
    expect(trace.lastIndexOf("validation")).toBeGreaterThan(lastGenerate);
    expect(trace.lastIndexOf("reasoning")).toBeGreaterThan(lastGenerate);
    expect(trace.lastIndexOf("attestations")).toBeGreaterThan(lastGenerate);
  });

  it("runs the finalizers exactly once per stable pass", async () => {
    await runCasePipeline("case-1", "firm-1");
    expect(trace.filter((s) => s === "validation")).toHaveLength(1);
    expect(trace.filter((s) => s === "reasoning")).toHaveLength(1);
    expect(trace.filter((s) => s === "attestations")).toHaveLength(1);
  });

  it("coalesces a request arriving DURING finalization into another complete pass", async () => {
    let validations = 0;
    validationImpl = async () => {
      validations += 1;
      // A reviewer publishes a note while the findings are being written.
      if (validations === 1) row.pipelineRerunRequested = true;
    };
    const out = await runCasePipeline("case-1", "firm-1");
    // Deterministic: it is not dropped, and it is not run concurrently. It
    // earns a whole further pass, generation included.
    expect(out.passes).toBe(2);
    expect(trace.filter((s) => s === "generate")).toHaveLength(2);
    expect(trace.filter((s) => s === "attestations")).toHaveLength(2);
  });

  // The no-omission contract, end to end through the real finalizer chain.
  it("honours every obligation before returning, past the former three-pass cap", async () => {
    let generated = 0;
    const OBLIGATIONS = 7;
    generateImpl = async () => {
      generated += 1;
      if (generated <= OBLIGATIONS) row.pipelineRerunRequested = true;
    };
    const out = await runCasePipeline("case-1", "firm-1");
    expect(out.passes).toBe(OBLIGATIONS + 1);
    // Every pass was COMPLETE — generation followed by all three finalizers.
    expect(trace.filter((s) => s === "generate")).toHaveLength(OBLIGATIONS + 1);
    expect(trace.filter((s) => s === "validation")).toHaveLength(OBLIGATIONS + 1);
    expect(trace.filter((s) => s === "reasoning")).toHaveLength(OBLIGATIONS + 1);
    expect(trace.filter((s) => s === "attestations")).toHaveLength(OBLIGATIONS + 1);
    // Nothing is owed, and nothing is waiting for a caller that will not come.
    expect(row.pipelineRerunRequested).toBe(false);
    expect(trace[trace.length - 1]).toBe("attestations");
  });

  it("an edit during the LAST finalizer still earns a complete pass", async () => {
    let attestations = 0;
    // The narrowest window: the flag is set by the final stage of a pass.
    vi.mocked(await import("@/lib/engine/attestationService")).refreshCaseAttestations.mockImplementation(async () => {
      trace.push("attestations");
      attestations += 1;
      if (attestations === 1) row.pipelineRerunRequested = true;
    });
    const out = await runCasePipeline("case-1", "firm-1");
    expect(out.passes).toBe(2);
    expect(trace.filter((s) => s === "generate")).toHaveLength(2);
    expect(row.pipelineRerunRequested).toBe(false);
  });

  it("a thrown finalizer does not lose the generated plan, and is reported", async () => {
    validationImpl = async () => { throw new Error("validation exploded"); };
    const out = await runCasePipeline("case-1", "firm-1");
    // Generation stands; the later finalizers still ran.
    expect(trace).toEqual(["generate", "validation", "reasoning", "attestations"]);
    expect(out.finalizerErrors).toEqual([{ stage: "validation", message: "validation exploded" }]);
    expect(out.futureCare).toBe(34);
    // …and the lock is released, not leaked.
    expect(row.pipelineRunId).toBeNull();
  });

  it("a thrown generation aborts the pass and releases the lock", async () => {
    generateImpl = async () => { throw new Error("generation exploded"); };
    await expect(runCasePipeline("case-1", "firm-1")).rejects.toThrow("generation exploded");
    expect(trace).toEqual(["generate"]);
    expect(row.pipelineRunId).toBeNull();
  });

  it("refuses an overlapping caller and records its intent", async () => {
    let second: unknown = null;
    generateImpl = async () => {
      if (trace.filter((s) => s === "generate").length === 1) {
        second = await runCasePipeline("case-1", "firm-1").catch((e) => e);
      }
    };
    await runCasePipeline("case-1", "firm-1");
    expect(second).toBeInstanceOf(PipelineBusyError);
    // Its intent was not dropped: the holder made another complete pass.
    expect(trace.filter((s) => s === "generate")).toHaveLength(2);
    expect(trace.filter((s) => s === "attestations")).toHaveLength(2);
  });

  it("never interleaves two passes", async () => {
    let inFlight = 0;
    let maxInFlight = 0;
    generateImpl = async () => {
      inFlight += 1;
      maxInFlight = Math.max(maxInFlight, inFlight);
      for (let i = 0; i < 5; i += 1) await Promise.resolve();
      inFlight -= 1;
    };
    await Promise.all([
      runCasePipeline("case-1", "firm-1").catch(() => null),
      runCasePipeline("case-1", "firm-1").catch(() => null),
      runCasePipeline("case-1", "firm-1").catch(() => null),
    ]);
    expect(maxInFlight).toBe(1);
  });

  it("leaves the case in a consistent final state after a contested run", async () => {
    let generated = 0;
    generateImpl = async () => {
      generated += 1;
      if (generated < 2) row.pipelineRerunRequested = true;
    };
    await runCasePipeline("case-1", "firm-1");
    expect(row.pipelineRunId).toBeNull();
    expect(row.pipelineRunAt).toBeNull();
    expect(row.pipelineRerunRequested).toBe(false);
    // The trace ends on a complete pass: never a generation with no finalizers.
    expect(trace[trace.length - 1]).toBe("attestations");
  });
});
