// Comprehensive list of medical specialties for the intake "Specialty" field.
// Descriptive only — the AI engine infers the injury-care category from the
// diagnosis, so this list can be as broad as clinical practice requires.
export const MEDICAL_SPECIALTIES: string[] = [
  "Allergy & Immunology",
  "Anesthesiology",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Critical Care Medicine",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology",
  "Family Medicine",
  "Gastroenterology",
  "General Surgery",
  "Geriatric Medicine",
  "Hand Surgery",
  "Hematology",
  "Hospitalist / Internal Medicine",
  "Infectious Disease",
  "Interventional Radiology",
  "Nephrology",
  "Neurology",
  "Neuropsychology",
  "Neurosurgery",
  "Obstetrics & Gynecology",
  "Occupational Medicine",
  "Occupational Therapy",
  "Oncology (Medical)",
  "Ophthalmology",
  "Oral & Maxillofacial Surgery",
  "Orthopedic Surgery",
  "Otolaryngology (ENT)",
  "Pain Management",
  "Palliative Care",
  "Pathology",
  "Pediatrics",
  "Physical Medicine & Rehabilitation (PM&R)",
  "Physical Therapy",
  "Plastic & Reconstructive Surgery",
  "Podiatry",
  "Prosthetics & Orthotics",
  "Psychiatry",
  "Psychology",
  "Pulmonology",
  "Radiation Oncology",
  "Radiology",
  "Rheumatology",
  "Speech-Language Pathology",
  "Sports Medicine",
  "Trauma Surgery",
  "Urology",
  "Vascular Surgery",
  "Vocational Rehabilitation",
];
